//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolManagementSystem.Models
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class Teacher
    {
        public int teacherID { get; set; }
        public string surname { get; set; }
        public string forename { get; set; }
        public System.DateTime dob { get; set; }
        public string phone { get; set; }
        public string type { get; set; }
        public Nullable<decimal> salary { get; set; }
        public string subjects { get; set; }
    }
}
